#ifndef ENGINELIMITS_INCLUDED
#define ENGINELIMITS_INCLUDED

enum {
	EL_MAX_VERTEX_IN_GROUP	= 4096,
	EL_MAX_INDEX_IN_GROUP	= 4096,
	EL_MAX_MODEL_GROUPS		= 8,
	EL_MAX_VERTEX_IN_MODEL	= EL_MAX_VERTEX_IN_GROUP * EL_MAX_MODEL_GROUPS,
	EL_MAX_INDEX_IN_MODEL	= EL_MAX_INDEX_IN_GROUP * EL_MAX_MODEL_GROUPS,
	EL_MAX_MODELS			= 1024,
	EL_MAX_MODEL_RESOURCES  = 128,
	EL_FILE_STRING_LEN		= 16,
};

#define EL_USE_FLOAT		1
//#define EL_BATCH_VERTICES	0
//#define EL_SHOW_MODELS

#endif